### PR TITLE
TEST: Converting existing spec tests to minitest format

### PR DESCRIPTION
**Pull request by SamAnast**
Converting syntax of existing spec tests to min test format.

Fixes # Helps to improve test coverage, and check for bugs

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by macite** [comment]
Is this ready for review? Remember to tag me when ready.

**Comment by macite** [comment]
Remember to delete the spec tests...

**Comment by linhhtr** [comment]
Hi @macite, could you please have a look at the tests after converted? I had a look and think they might be okay, I already told @SamAnast to delete the specs tests, he will commit the deletion

**Comment by macite** [comment]
The tests look fine - once the spec tests are deleted it will make it easier to compare the changes.

**Comment by macite** [comment]
Looks good. Well done.

**Pull request merged**
