### PR TITLE
Docker-compose

### PR DESCRIPTION
**Pull request by ohtake**
This PR will:

- make docker-compose working again
- install ffmpeg to support audio recording feature

### CODE REVIEW

**Comment by jakerenzella** [comment]
@ohtake Looks like it just might be missing LaTeX distribution? Otherwise, this is a good base for adding the rest of the native dependencies, I will pull this down and run the tests.

**Comment by macite** [comment]
Perhaps with this workflow we should look at dropping the separation between the two and just use MySQL in development and production.

**Comment by akashagarwal7** [comment]
Sounds good to me :) That'd help with the emoji thingy as well.

**Comment by ohtake** [comment]
`libpq-dev` has been moved from line 9 to line 20.
This change was not intended.
I will update the commit to minimize changes.

**Comment by ohtake** [comment]
Two tests passed:

* [x] (ffmpeg) Submit audio comments and listen to them
* [x] (latex) Submit tasks and view the generated PDFs

Shall I separte MySQL in this PR?
Or it should be in another PR?

**Comment by jakerenzella** [comment]
@ohtake Looks good so far, let's just keep it in this PR, we can merge when ready 👍

**Comment by ohtake** [comment]
I had a talk with @jakerenzella about reloading the API without restarting a Docker container.
Excluding `.bundle` and `tmp` directories enables Dockerized rails app to reload itself.

Similar approach may be applied to the web project but it requires modifications on Grunt tasks.
Changes for the web are commented out for now.

**Comment by ohtake** [comment]
Finally, managed to dockerize the api and web with live-reloading feature.
Changes in source code will be automatically applied to Docker containers without restarting them.

## Usage

```bash
export DF_DOCKER_MACHINE_IP=192.0.2.1 # Replace it for your own env
cd doubtfire-api
docker-compose build
docker-compose up -d
# wait a few seconds
docker-compose exec api bundle exec rake db:populate
```

Open <http://localhost:8000/> for Angular 1 project ('development' branch in web) or <http://localhost:4200/> for Angular 6 project ('quality/decafinate' branch in web).

## Merging strategy

Because of dependencies and duplicated commits, it is better to merge PRs in the following order.

1. Merge doubtfire-lms/doubtfire-web#129 into 'development'
1. Merge 'development' into 'quality/decafinate'
1. Rebase doubtfire-lms/doubtfire-web#133 onto 'quality/decafinate'
1. Merge doubtfire-lms/doubtfire-web#133 into 'quality/decafinate'
1. Merge this PR

**Pull request merged**
