### PR TITLE
Enhance/add time submitted and assessed

### PR DESCRIPTION
**Pull request by Reubsinit**
This all works on my end. Let me know what you guys think @macite @alexcu. Was I supposed to omit the changes to schema so you could run the `rake db:migrate` with the script I added?

### CODE REVIEW

**Comment by Reubsinit** [comment]
Also, I was thinking, what about students who have already submitted things before this change?

So I was thinking for those who have already submitted:
```if times_assessed > 0 and times_submitted == 0 then times_submitted = times_assessed - 1```

**Comment by macite** [comment]
In submits can you change it to only increment the number of submissions if the task is not currently in the ready to mark status.

**Comment by macite** [comment]
Also need to include an update to the latex task cover sheet. Add time so submission, times assessed and submitted, and students id. Could also add a list of comments if we can get it to fit.

**Comment by Reubsinit** [comment]
@macite Was going to wait to ask you about latex because the dev version doesn't seem to render any pdfs on the tasks I tried to submit through. So I can't actually see my changes.

**Comment by Reubsinit** [comment]
and also, do you want something like:
```def submit(submit_date = Time.zone.now)
      if self.task_status != TaskStatus.ready_to_mark
           self.times_submitted += 1
      self.task_status      = TaskStatus.ready_to_mark
      self.submission_date  = submit_date```

or 

```def submit(submit_date = Time.zone.now)
      if self.task_status != TaskStatus.ready_to_mark
           self.times_submitted += 1
           self.task_status      = TaskStatus.ready_to_mark
      self.submission_date  = submit_date```

**Comment by Reubsinit** [comment]
Also, in that conditional, do you want to assign the task status to complete as well as incrementing the submission count? Because if the task status is not complete upon submitting, then it should only really be complete then.

**Comment by macite** [comment]
You can generate the PDFs using rake submission:generate_pdfs. You can then download the PDFs but not view them with the local host server.

cheers,
Andrew

**Comment by Reubsinit** [comment]
@macite Should be good to go.

**Comment by macite** [comment]
@Reubsinit looking good. I'll merge it when I'm back during the week.

**Pull request merged**
