### PR TITLE
CONFIG: Switch from FactoryGirl to FactoryBot in development branch

### PR DESCRIPTION
**Pull request by llyyer**
# Description

- Switch from FactoryGirl to FactoryBot in development branch
- Improve break test, group test and task status test
- Add a test file for all controllers

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by llyyer** [comment]
hello andrew, i have improved something in break test and task status test.

**Comment by llyyer** [comment]
@macite Hello Andrew, i have switch FactoryGirl to FactoryBot in this development branch. can you check this?

**Comment by macite** [comment]
@llyyer you need to resolve the conflicts before I can consider this.

**Comment by macite** [comment]
Conflicts means that there are changes that have been made to the development branch that are not in your branch - and that the changes you are making cannot be automatically merged. So you need to fetch the changes from the main repository and then manually merge them into your branch. Most likely these are new tests that have been added since you forked the repository and made these changes. It will be important to take care in merging these branches - you want mostly to take in the changes that are in development on the main repo and then adjust them to use FactoryBot.

Hope that helps.

**Comment by llyyer** [comment]
@macite Hello Andrew, the changes can run successfully in CI. Can you check again? thanks.

**Comment by llyyer** [comment]
@macite ,Hello Andrew, there are many errors show that Factory not registered something. I have no idea about how to fix them, can you give me some suggestions?

**Comment by macite** [comment]
Can you enable me to contribute to this PR?

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by macite** [comment]
I've got a fix that should correct the issues you have identified.

**Comment by llyyer** [comment]
Yesterday I went to the website and found that it was already ticked. I thought it was someone who helped me check.

**Pull request merged**
