### PR TITLE
Feature/add paul rake seed data

### PR DESCRIPTION
**Pull request by PaulTsevas**
Add my own user to the populate the rake db populate task

### CODE REVIEW

**Comment by alexcu** [comment]
@psuedoSudo Please do not write one-word commit messages as this really does not describe what the commit does. Refer to our `CONTRIBUTING.md` file.

This commit really doesn't add much functionality—does it need to be a pull request? Or are you guys practising with making PRs?

**Comment by psuedoSudo** [comment]
Correct. In theory there should/will be one from each team member to make sure they start becoming aware of your contributing guidelines.

**Comment by alexcu** [comment]
Have a look at that document to help resolve the merge conflict correctly also as this PR can't go through otherwise

**Comment by macite** [comment]
Has conflicts that have not been resolved...

**Pull request closed without merging**
